intro:
	g++ -Wextra -Wall intro.cpp -o intro

intbox:
	g++ -Wextra -Wall intbox.cpp intbox.hpp -o intbox

ncurses:
	g++ -Wextra -Wall ncursestest.cpp -o ncurses -lncurses

bfs:
	g++ -Wextra -Wall bfstraverse.cpp -o bfs

clean:
	rm -f intro intbox ncurses *.o