stack:
	g++ -Wextra -Werror -Wall stack.cpp -o stack

queue:

bt:
	g++ -Wextra -Werror -Wall binarytree.cpp -o bt

generics:
	g++ -Wextra -Werror -Wall generics.cpp -o generics

main:
	g++ -Wextra -Wall main.cpp -o main

clean:
	rm -f *.o stack bt generics gstack main