intro:
	gcc -Wall -Wextra -g intro.c intro.h -o intro

dll:
	gcc -Wall -Wextra -g dll.c dll.h -o dll

sll:
	gcc -Wall -Wextra -g sll.c sll.h -o sll

funcptr:
	gcc -Wall -Wextra -g funcptr.c funcptr.h -o funcptr

examprep:
	gcc -Wall -Wextra -g examprep.c -o prep

clean:
	rm -rf *.o intro dll sll prep funcptr